package Animations;

public enum ActionState {
    STAND, RUN, DUCK, STARTJUMP, JUMP,

    ATTACK1, ATTACK2, ATTACK3, ATTACK4, ATTACK5, ATTACK6, ATTACK7, ATTACK8, ATTACK9, ATTACK10,
    ATTACK11, ATTACK12, ATTACK13, ATTACK14, ATTACK15, ATTACK16, ATTACK17, ATTACK18, ATTACK19, ATTACK20, ATTACK21, FLASHCOMBO,

    DEAD, DEAD01, FLYAWAY, HURT1, HURT2, JUMPOFF, LAND01, LANDH, ROLLBACK, ROLLBACK2, ROLLFRONT, ROLLFRONT2, UPP, WALLED,

    CHARGING, BLAST,

    TEST1, TEST2
}
